// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtwtsUJ3fLCXLr13_qlp5lDkO39hM76Gw',
    appId: '1:991912902790:web:7be33799d5e99dbd861107',
    messagingSenderId: '991912902790',
    projectId: 'news-1a714',
    authDomain: 'news-1a714.firebaseapp.com',
    storageBucket: 'news-1a714.appspot.com',
    measurementId: 'G-Q61EQQR26C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlqSegTY4hvWAlBOYbsU2RfWM0I_SAJFc',
    appId: '1:991912902790:android:135b0ca503a54d0e861107',
    messagingSenderId: '991912902790',
    projectId: 'news-1a714',
    storageBucket: 'news-1a714.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWRbiTLJWx1y19XR1Rzfyo-FsBfknYBqo',
    appId: '1:991912902790:ios:19698bf2a4d8e86d861107',
    messagingSenderId: '991912902790',
    projectId: 'news-1a714',
    storageBucket: 'news-1a714.appspot.com',
    iosBundleId: 'com.example.newsAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWRbiTLJWx1y19XR1Rzfyo-FsBfknYBqo',
    appId: '1:991912902790:ios:19698bf2a4d8e86d861107',
    messagingSenderId: '991912902790',
    projectId: 'news-1a714',
    storageBucket: 'news-1a714.appspot.com',
    iosBundleId: 'com.example.newsAppFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtwtsUJ3fLCXLr13_qlp5lDkO39hM76Gw',
    appId: '1:991912902790:web:0b11e1a537c6c18b861107',
    messagingSenderId: '991912902790',
    projectId: 'news-1a714',
    authDomain: 'news-1a714.firebaseapp.com',
    storageBucket: 'news-1a714.appspot.com',
    measurementId: 'G-57PQD2L9TK',
  );
}
